name: ci
on:
  push:
    branches:
      - master
jobs:
  cypress-test-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install cypress
        run: npm install
      - name: Run cypress tests
        run: npm run test:ci:dashboard
        env:
          DASHBOARD_KEY: ${{ secrets.DASHBOARD_KEY }}
  cypress-test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install cypress
        run: npm install
      - name: Run cypress tests
        run: npm run test:ci:dashboard
        env:
          DASHBOARD_KEY: ${{ secrets.DASHBOARD_KEY }}
  cypress-test-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install cypress
        run: npm install
      - name: Run cypress tests
        run: npm run test:ci:dashboard
        env:
          DASHBOARD_KEY: ${{ secrets.DASHBOARD_KEY }}
